name: tekwise
on:
  push:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          clean: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm i --force

      - name: Build application
        run: CI=false npm run build && cp -R ./.github/ root@tekwise:/var/www/html/app.bidvid/
